config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'

  devise_for :users

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create] do
      resources :likes, only: [:create]
      resources :comments, only: [:index, :new, :create]
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#index"

  namespace :api do
    namespace :v1 do
      resources :users, only: [] do
        resources :posts, only: [:index] do
          resources :comments, only: [:index, :new, :create]
        end
      end
    end
  end
end

app/models/ability.rb
# app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    #  user ||= User.new # Guest user (not logged in)
    return unless user.present?

    can :read, :all
    can :create, [Comment, Post]

    # User can destroy their own posts and comments
    can :destroy, Post, author: user.id
    can :destroy, Comment, user: user.id

    # Admins can delete any post or comment
    can :destroy, Post, author: user.id, role: 'admin'
    can :destroy, Comment, user: user.id, role: 'admin'
  end
end
# class Ability
#   include CanCan::Ability

#   def initialize(user)
#     return unless user.present?

#     can :read, :all
#     can :create, [Comment, Post]
#     if user.role == 'admin'
#       can :manage, :all
#     else
#       can :destroy, Comment, user: user
#       can :destroy, Post, author: user
#     end
#   end
# end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  belongs_to :author, class_name: 'User'
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  before_create :increment_user_posts_counter
  before_create :set_defaults

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  private

  def increment_user_posts_counter
    author.increment!(:posts_counter)
  end

  def set_defaults
    self.likes_counter ||= 0
    self.comments_counter ||= 0
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :posts, foreign_key: 'author_id', dependent: :destroy
  has_many :comments, foreign_key: 'user_id', dependent: :destroy
  has_many :likes, foreign_key: 'user_id', dependent: :destroy

  def most_recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < ApplicationController
  skip_before_action :authenticate_user!
  protect_from_forgery with: :null_session

  def index
    @post = Post.find(params[:post_id])
    @comments = @post.comments

    if @comments
      render json: { status: 'Success', message: 'Comment fetched successfully', data: @comments }, status: :ok
    else
      render json: { status: 'Error', message: 'No comments found!', data: @comments.errors },
             status: :bad_request
    end
  end

  def create
    @user = User.find(params[:user_id])
    @post = Post.find(params[:post_id])
    @comments = @post.comments.new(comment_params)
    @comments.post_id = @post.id
    @comments.user_id = @user.id

    if @comments.save
      render json: { status: 'Success', message: 'Comment Created', data: @comments }, status: :ok
    else
      render json: { status: 'Not Found', message: 'Details not found', data: @comments.errors },
             status: :unprocessable_entity
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end

  skip_before_action :verify_authenticity_token, only: [:create]
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  skip_before_action :authenticate_user!
  protect_from_forgery with: :null_session
  protect_from_forgery with: :exception, except: [:create]

  def index
    @posts = Post.includes(:author).where(author_id: params[:user_id])
    @user = User.find(params[:user_id])

    if @posts
      render json: { status: 'Success', message: 'Bravo!', data: @posts }, status: :ok
    else
      render json: { status: 'Error', message: 'OOPSY Daisy!', errors: @posts.errors }, status: :bad_request
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :comments_counter, :likes_counter)
  end

  skip_before_action :verify_authenticity_token, only: [:create]
end

app/controllers/concerns/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,
                except: %i[index show]
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    attributes = [:name]
    devise_parameter_sanitizer.permit(:sign_up, keys: attributes)
    devise_parameter_sanitizer.permit(:account_update, keys: attributes)
  end
end

app/controllers/concerns/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource
  # before_action :authenticate_user!, except: :index
  before_action :authenticate_user!, only: %i[new create destroy]

  def index
    @user = User.find(params[:user_id])
    @post = Post.find(params[:post_id])
    @comments = @post.comments
  end

  def new
    @user = User.find(params[:user_id])
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  def create
    @user = User.find(params[:user_id])
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.user = @user
    if @comment.save
      redirect_to user_post_path(@user, @post), notice: 'Comment created!'
    else
      flash.now[:errors] = 'Invalid comment!'
      render :new
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])

    if @comment.destroy
      redirect_to user_post_path(@user, @post), flash[:notice] = 'Comment deleted!'
    else
      redirect_to user_post_path(@user, @post), alert: 'OOPSY Daisy!'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/concerns/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource except:
  %i[index show]

  def index
    @posts = Post.includes(:author).where(author_id: params[:user_id])
    @user = User.find(params[:user_id])
  end

  def show
    # @post = Post.includes(:author).find_by(author_id: params[:user_id], id: params[:id])
    @post = Post.includes(:author).find(params[:id])

    if @post
      @user = @post.author
      @comments = @post.comments
      # @comments = Post.find(@post.id).comments

    else
      flash[:alert] = 'Post not found'
      redirect_to user_posts_path(params[:user_id])
    end
  end

  def new
    @user = current_user
    @post = Post.new
  end

  def create
    @user = current_user
    @post = @user.posts.new(post_params)
    if @post.save
      redirect_to user_post_path(@user, @post), notice: 'Post created successfully!'
    else
      puts @user
      puts @post.errors.full_messages
      flash.now[:errors] = 'Invalid post!'
      render :new
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])
    @post.likes.destroy_all
    @post.comments.destroy_all
    @post.destroy
    redirect_to user_posts_path(@user)
  end

  private

  def post_params
    params.require(:post).permit(:title, :text, :likes_counter, :comments_counter)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end
end

app/helpers/api/v1/comments_helper.rb
module Api::V1::CommentsHelper
end

app/helpers/api/v1/posts_helper.rb
module Api::V1::PostsHelper
end

app/helpers/api/v1/users_helper.rb
module Api::V1::UsersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/comment.html.erb
<% stylesheet_link_tag('index')%>
<div class="comment-container">
<h3>Add a new Comment</h3>
<div class="comment-form">
</div>
</div>

app/views/comments/index.html.erb
<!-- app/views/comments/index.html.erb -->
<h1>Comments for <%= @post.title %></h1>

<% @comments.each do |comment| %>
  <div class="comment">
    <p><strong><%= comment.user.name %>:</strong> <%= comment.text %></p>
     <% if can?(:destroy, comment) %>
      <%= button_to 'Delete Comment', user_post_comment_path(@user, @post, comment), method: :delete, data: { confirm: 'Are you sure you want to delete this comment?' }, class: 'delete-button' %>
    <% end %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
     <% if flash[:notice].present? %>
      <div>
        <%= flash[:notice] %>
      </div>
    <% end %>
    <% if flash[:alert].present? %>
      <div>
        <%= flash[:alert] %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<div class="posts-container">
<div class="users">
<%= render 'shared/user', user:@user %>
</div>

<div class="posts">
<h2>All Posts</h2>

<%=link_to "Add post", new_user_post_path(@user)%>

<% @posts.each do |post| %>
<%= render 'shared/post', post: post, user:@user %>

<div class="post-content">
<%= link_to "Add Comment", new_user_post_comment_path(@user, post) %>

<%= form_with url: user_post_likes_path(post.author.id, post.id) do |form| %>

<%= form.submit 'Like' %>
<% end %>

<% if can?(:destroy, @post) %>
        <%= button_to 'Delete Post', user_post_path(@post.author_id, @post), method: :delete, data: { confirm: 'Are you sure you want to delete this post?' }, class: 'delete-button' %>
      <% end %>
</div>

<% if post.recent_comments.present? %>
<% comments = post.recent_comments %>
<%= render "shared/comments", comments:comments %>
<% end %>
<% end %>
</div>
</div>

app/views/posts/new.html.erb
<div class= "post-form">
  <h2 class= "create-post">Create a post</h2>

  <%# <%= form_with model: @post, url: user_posts_path(@user) do |f| %> 
  <%= form_with(model: [@user, @post], url: user_posts_path(@user)) do |f| %>
    <div class= "title-input">
      <%= f.label :title %>
      <%= f.text_field :title, required: true %>
    </div>

    <div class= "comment-input">
      <%= f.label :text %>
      <%= f.text_field :text, required: true %>
    </div>
<!-- Add fields for likes_counter and comments_counter -->
    <div class="likes-counter-input">
      <%= f.label :likes_counter %>
      <%= f.number_field :likes_counter, value: 0, min: 0 %>
    </div>

    <div class="comments-counter-input">
      <%= f.label :comments_counter %>
      <%= f.number_field :comments_counter, value: 0, min: 0 %>
    </div>
    
    <div class= "submit">
      <%= f.submit "Submit" %>
    </div>
    <% if @post.errors.any? %>
  <div class="error-messages">
    <h2>Errors:</h2>
    <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
         <% end %>
    </ul>
  </div>
  <% end %>
 <% end %>
</div>

app/views/posts/show.html.erb
<div class="posts-show">
<div class="post-show">

<div class="post-title-show">
<h1><%= @post.title %></h1>

<div class="post-interact">
<p>comments: <%= @post.comments_counter %></p>
<p>likes: <%= @post.likes_counter %></p>
</div>
</div>

<div>
<p><%= @post.text %></p>
</div>

</div>
<div class= "shared-comment-cont">
<div class="shared-comments">
<%= link_to "Add Comment", new_user_post_comment_path(@user, @post) %>
<%= form_with url: user_post_likes_path(@post.author.id, @post.id) do |form| %>
<%= form.submit 'Like' %>
<% end %>

<% if can? :destroy, @post %>
  <%= button_to 'Delete Post', user_post_path(@post.author, @post), method: :delete, data: { confirm: 'Are you sure you want to delete this post?' }, class: 'delete-button' %>
<% end %>

</div>
<h2>Comments</h2>
<%= render "shared/comments", comments:@comments %>
</div>

</div>

app/views/shared/_comments.html.erb
<div class="comments">
  <% comments.each do |comment| %>
    <div class="comment">
      <p><%= comment.user.name%> :<%= comment.text %></p>
<% if can? :destroy, @comment %>
  <%= button_to 'Delete Comment', user_post_comment_path(comment.user, comment.post_id, comment), method: :delete, data: { confirm: 'Are you sure you want to delete this comment?' }, class: 'delete-button' %>
<% end %>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<% if user_signed_in? %>
<div> Welcome <%= current_user.email %> </div>
<%= button_to "Sign out", destroy_user_session_path, method: :delete %>
<% else %>
<%= button_to "Sign in", new_user_session_path %>
<% end %>

<div class="users">
<% @users.each do |user| %>
<%= render 'shared/user', user:user %>
<% end %>
</div>